# Builds the Play Store release App Bundle after verifying that every
# required piece of release configuration is present.
#
# Usage (from the repo root):   .\scripts\build_release.ps1
# Output: build\app\outputs\bundle\release\app-release.aab

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root
$problems = @()

# 1. Firebase client config (gitignored; generated by `flutterfire configure`)
$fbOptions = 'lib/firebase_options.dart'
if (-not (Test-Path $fbOptions)) {
    $problems += "$fbOptions is missing - run 'flutterfire configure'."
} elseif (Select-String -Path $fbOptions -Pattern "android = FirebaseOptions\(\s*apiKey: 'REPLACE_WITH" -Quiet) {
    $problems += "$fbOptions still contains placeholder Android values."
}
if (-not (Test-Path 'android/app/google-services.json')) {
    $problems += 'android/app/google-services.json is missing.'
}

# 2. Build-time defines
if (-not (Test-Path '.env')) {
    $problems += '.env is missing (copy .env.example and fill in the values).'
} else {
    $rcLine = Select-String -Path '.env' -Pattern '^REVENUECAT_ANDROID_API_KEY=(.*)$'
    $rcKey = if ($rcLine) { $rcLine.Matches[0].Groups[1].Value.Trim() } else { '' }
    if ($rcKey.StartsWith('sk_') -or $rcKey.StartsWith('rc_')) {
        $problems += 'REVENUECAT_ANDROID_API_KEY is a SECRET key (sk_/rc_). Never ship it in the app: use the public goog_ key, and rotate the secret key in RevenueCat if any build containing it was shared.'
    } elseif (-not $rcKey.StartsWith('goog_') -or $rcKey -like 'goog_your*') {
        $problems += 'REVENUECAT_ANDROID_API_KEY in .env must be your real Google Play public key (goog_...).'
    }
}

# 3. Release signing (upload key)
$keyProps = @('android/app/key.properties', 'android/key.properties') | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $keyProps -and -not $env:ANDROID_KEYSTORE_PATH) {
    $problems += 'No signing config: create android/app/key.properties (see android/key.properties.example).'
} elseif ($keyProps) {
    $storeLine = Select-String -Path $keyProps -Pattern '^storeFile=(.*)$'
    if ($storeLine) {
        $storeFile = $storeLine.Matches[0].Groups[1].Value.Trim()
        $resolved = if ([IO.Path]::IsPathRooted($storeFile)) { $storeFile } else { Join-Path 'android/app' $storeFile }
        if (-not (Test-Path $resolved)) { $problems += "Keystore not found at $resolved." }
    }
}

if ($problems.Count -gt 0) {
    Write-Host "Release build blocked:" -ForegroundColor Red
    $problems | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    exit 1
}

flutter build appbundle --release --dart-define-from-file=.env --obfuscate --split-debug-info=build/symbols
