#!/usr/bin/env bash
# Builds the Play Store release App Bundle after verifying that every
# required piece of release configuration is present.
#
# Usage (from the repo root):   ./scripts/build_release.sh
# Output: build/app/outputs/bundle/release/app-release.aab
set -euo pipefail
cd "$(dirname "$0")/.."
problems=()

# 1. Firebase client config (gitignored; generated by `flutterfire configure`)
if [[ ! -f lib/firebase_options.dart ]]; then
  problems+=("lib/firebase_options.dart is missing - run 'flutterfire configure'.")
elif grep -Pzq "android = FirebaseOptions\(\s*apiKey: 'REPLACE_WITH" lib/firebase_options.dart; then
  problems+=("lib/firebase_options.dart still contains placeholder Android values.")
fi
[[ -f android/app/google-services.json ]] || problems+=("android/app/google-services.json is missing.")

# 2. Build-time defines
if [[ ! -f .env ]]; then
  problems+=(".env is missing (copy .env.example and fill in the values).")
else
  rc_key="$(grep -E '^REVENUECAT_ANDROID_API_KEY=' .env | cut -d= -f2- | tr -d '[:space:]' || true)"
  if [[ "$rc_key" == sk_* || "$rc_key" == rc_* ]]; then
    problems+=("REVENUECAT_ANDROID_API_KEY is a SECRET key (sk_/rc_). Use the public goog_ key and rotate the secret key in RevenueCat.")
  elif [[ "$rc_key" != goog_* || "$rc_key" == goog_your* ]]; then
    problems+=("REVENUECAT_ANDROID_API_KEY in .env must be your real Google Play public key (goog_...).")
  fi
fi

# 3. Release signing (upload key)
key_props=""
for f in android/app/key.properties android/key.properties; do
  [[ -f "$f" ]] && { key_props="$f"; break; }
done
if [[ -z "$key_props" && -z "${ANDROID_KEYSTORE_PATH:-}" ]]; then
  problems+=("No signing config: create android/app/key.properties (see android/key.properties.example).")
fi

if (( ${#problems[@]} > 0 )); then
  echo "Release build blocked:" >&2
  printf '  - %s\n' "${problems[@]}" >&2
  exit 1
fi

flutter build appbundle --release --dart-define-from-file=.env \
  --obfuscate --split-debug-info=build/symbols
